root_dir = 'E:\Datasets\mpi_inf_3dhp';
cams = [0, 1, 2, 4, 5, 6, 7, 8] + 1;
scaler = 368 / 2048;

% if exist([root_dir, '\annot_h5'],'dir')~=0
%     rmdir([root_dir, '\annot_h5'], 's');
% end
% mkdir([root_dir, '\annot_h5']);

fprintf('convert annotation data to hdf5 format file in %s\n', root_dir)
for i=1:8  % S1-S8
    for j=1:2  % Seq1-Seq2
        load(sprintf('%s\\S%d\\Seq%d\\annot.mat', root_dir, i, j))
        for k=cams
            % create annot2/video_X
            h5create(sprintf('%s\\annots.h5', root_dir),...
                sprintf('/S%d/Seq%d/annot2/video_%d', i, j, k-1),...
                [size(annot2{k,1}, 2), size(annot2{k,1}, 1)],...
                'Datatype', 'double');
            % create annot3/video_X
            h5create(sprintf('%s\\annots.h5', root_dir),...
                sprintf('/S%d/Seq%d/annot3/video_%d', i, j, k-1),...
                [size(annot3{k,1}, 2), size(annot3{k,1}, 1)],...
                'Datatype', 'double');
            % create univ_annot3/video_X
            h5create(sprintf('%s\\annots.h5', root_dir),...
                sprintf('/S%d/Seq%d/univ_annot3/video_%d', i, j, k-1),...
                [size(univ_annot3{k,1}, 2), size(univ_annot3{k,1}, 1)],...
                'Datatype', 'double');
            % write annot2/video_X
            h5write(sprintf('%s\\annots.h5', root_dir),...
                sprintf('/S%d/Seq%d/annot2/video_%d', i, j, k-1),...
                annot2{k,1}'*scaler);
            % write annot3/video_X
            h5write(sprintf('%s\\annots.h5', root_dir),...
                sprintf('/S%d/Seq%d/annot3/video_%d', i, j, k-1),...
                annot3{k,1}'*scaler);
            % write univ_annot3/video_X
            h5write(sprintf('%s\\annots.h5', root_dir),...
                sprintf('/S%d/Seq%d/univ_annot3/video_%d', i, j, k-1),...
                univ_annot3{k,1}'*scaler);
        end
    end
end
disp('done.')